# Generated by Django 3.2.7 on 2021-10-05 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=1000)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('in_review', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('assiged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='files/%y/%m/%d')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.task')),
            ],
        ),
    ]
