# Generated by Django 3.2.7 on 2021-10-20 04:46

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('remarks', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('in_review', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
